echo "/////////////////// DEVAFORM //////////////////"
echo "Completed installing Ruby (Ruby on Rails)"
echo ""
echo "You should be all set up but"
echo "Please end this instance of your terminal" 
echo "and start a new one for good measure"
echo ""